[package]
name = "tsp"
version = "0.1.0"
authors = ["Ben Lu <ayroblu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tsp"
path = "src/main.rs"

[dependencies]
libtsp = { path = "../libtsp" }
